default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DB_USER'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'postgres' %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bootcamp_ecommerce_api_development

test:
  <<: *default
  database: bootcamp_ecommerce_api_test

production:
  <<: *default
  database: bootcamp_ecommerce_api_production
  username: bootcamp_ecommerce_api
  password: <%= ENV['BOOTCAMP_ECOMMERCE_API_DATABASE_PASSWORD'] %>
